#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2022. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
---
- name: "[{{wd_activity.name}}/{{wd_action.name}}/{{wd_step.name}}]: Process step '{{ wd_step.name }}' for action '{{ wd_action.name }}' and activity '{{ wd_activity.name }}'"
  block:

    - set_fact:
         current_step_name: "{{wd_activity.short_name | lower if wd_activity.short_name is defined else wd_activity.name |lower}}\
                            >{{wd_action.short_name | lower if wd_action.short_name is defined else wd_action.name |lower}}\
                            >{{wd_step.short_name | lower if wd_step.short_name is defined else wd_step.name |lower}}"
         wd_task_name: "{{ wd_step | json_query (\"properties[?key == 'template'].value\") | first | default('')}}"
         wd_var_task_name: "{{ wd_step | json_query (\"properties[?key == 'var_template'].value\") | first | default('')}}"
         wd_run_var_name: "{{ 'run_' + wd_activity.short_name + '_' + wd_action.short_name + '_' + wd_step.short_name if wd_activity.short_name is defined and wd_action.short_name is defined and wd_step.short_name is defined else ''}}"
      tags:
        - always

    - name: "[{{current_step_name}}]: Verify the presence of the step task"
      task_loc:
         task_name: "{{wd_task_name}}"
         var_task_name: "{{wd_var_task_name}}"
         role_path: "{{role_path}}"
         tasks_folder: "{{wd_tasks_folder}}"
         step: "{{wd_step}}"
         verbose: "{{wd_no_log_flag | bool}}"
      register: wd_task_loc_result
      tags:
        - always

    - name: "[{{current_step_name}}]: Process task '{{ wd_task_loc_result.wd_task_filename }}' for step {{ wd_step.name }}, action '{{ wd_action.name }}' and activity '{{ wd_activity.name }}'"
      include_tasks: "{{wd_task_loc_result.wd_task_filename_path}}"
      register: step_result
      vars:
         wd_run_var_name_value: "{{ lookup('vars', wd_run_var_name, default='') }}"
         wd_run_when: "{{ wd_run_var_name_value if wd_run_var_name_value != '' else  wd_activity |\
                         ibm.ibm_zos_wazi_deploy.tag_filter (\
                            wd_activity.tags if wd_activity.tags is defined else None,\
                            wd_action.tags if wd_action.tags is defined else None,\
                            wd_step.tags if wd_step.tags is defined else None,\
                            planTags if planTags is defined else wd_deployment_plan.default_tags | join(',') if wd_deployment_plan.default_tags is defined else None ,\
                            planSkipTags if planSkipTags is defined else wd_deployment_plan.default_skip_tags | join(',') if wd_deployment_plan.default_skip_tags is defined else None ,\
                            3,
                            wd_no_log_flag
                         ) }}"
      when: wd_run_when == True
      tags:
        - always
