#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2023. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
---
- name: "[{{current_step_name}}]"
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"
  block:
    - set_fact: 
       wd_ignore_errors_var : "{{wd_zos_module.ignore_errors if wd_zos_module.ignore_errors is defined else False}}"
         
    - name: "[{{current_step_name}}]: Copy {{wd_zos_module.src}} to {{wd_zos_module.dest}}"
      zos_copy:
        backup: "{{ wd_zos_module.backup | default(omit) }}"
        backup_name: "{{ wd_zos_module.backup_name | default(omit) }}"
        content: "{{ wd_zos_module.content | default(omit) }}"
        dest: "{{ wd_zos_module.dest | mandatory }}"
        dest_data_set: "{{ wd_zos_module.dest_data_set | default(omit) }}"
        encoding: "{{ wd_zos_module.encoding | default(omit) }}"
        force: "{{ wd_zos_module.force | default(omit) }}"
        ignore_sftp_stderr: "{{ wd_zos_module.ignore_sftp_stderr | default(omit) }}"
        is_binary: "{{ wd_zos_module.is_binary | default(omit) }}"
        local_follow: "{{ wd_zos_module.local_follow | default(omit) }}"
        mode: "{{ wd_zos_module.mode | default(omit) }}"
        remote_src: "{{ wd_zos_module.remote_src | default(omit) }}"
        sftp_port: "{{ wd_zos_module.sftp_port | default(omit) }}"
        src: "{{ wd_zos_module.src | mandatory}}"
        validate: "{{ wd_zos_module.validate | default(omit) }}"
        volume: "{{ wd_zos_module.volume | default(omit) }}"
        block_size: "{{ wd_zos_module.block_size | default(omit) }}"
      register: wd_zos_module_result
      ignore_errors: "{{wd_ignore_errors_var}}"
      failed_when:
        - wd_zos_module_result.failed == true
        - wd_zos_module.ignore_error_message is not defined or wd_zos_module.ignore_error_message != wd_zos_module_result.msg 
 