#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2022. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
---
- name: "[{{current_step_name}}]"
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"
  block:
    - set_fact: 
       wd_ignore_errors_var : "{{wd_zos_module.ignore_errors if wd_zos_module.ignore_errors is defined else False}}"

    - name: "[{{current_step_name}}]: Query job status {{ wd_zos_module.job_name }}"
      zos_job_query:
        job_name: "{{ wd_zos_module.job_name | default(omit) }}"
        job_id: "{{ wd_zos_module.job_id | default(omit) }}"  
        owner: "{{ wd_zos_module.owner | default(omit) }}"
      register: wd_zos_module_result
      ignore_errors: "{{wd_ignore_errors_var}}"