#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2022. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
---
- name: "[{{current_step_name}}]"
  environment: "{{ environment_vars }}"
  block:
    - set_fact: 
       wd_ignore_errors_var : "{{wd_zos_module.ignore_errors if wd_zos_module.ignore_errors is defined else False}}"
       wd_timestamp: "{{ lookup('pipe','date +%s') }}"

    - name: "{{current_step_name}}]: Create {{wd_deploy_dir_local}}/cp.{{wd_timestamp}}.sh global shell script"
      template:
        src: cp-sh.j2
        dest: "{{wd_deploy_dir_local}}/cp.{{wd_timestamp}}.sh"
        mode: 0755
      delegate_to: localhost
      vars:
        wd_items: "{{ wd_zos_module.members| default([])}}"
        wd_ignore_missing: "{{ wd_zos_module.ignore_missing| default(False)}}"
      register: wd_zos_module_result
      changed_when: true
      ignore_errors: "{{wd_ignore_errors_var}}"

    - name: "{{current_step_name}}]: Copy {{wd_deploy_dir_local}}/cp.{{wd_timestamp}}.sh to {{wd_deploy_dir_uss}}/cp.{{wd_timestamp}}.sh"
      include_tasks: "task_zos_copy.yml"
      ignore_errors: "{{wd_ignore_errors_var}}"
      vars:
        wd_zos_module:
          src: "{{wd_deploy_dir_local}}/cp.{{wd_timestamp}}.sh"
          dest: "{{wd_deploy_dir_uss}}/cp.{{wd_timestamp}}.sh"
          remote_src: false
          is_binary: false
          encoding:
            from: utf8
            to: IBM-1047

    - name: "[{{current_step_name}}]: Copy the member(s) to destination PDS(s) with global shell script {{wd_deploy_dir_uss}}/cp.{{wd_timestamp}}.sh"
      shell: |
        #!/bin/sh
        set +e
        sh {{wd_deploy_dir_uss}}/cp.{{wd_timestamp}}.sh 2> {{wd_deploy_dir_uss}}/cp.{{wd_timestamp}}.log
        rc=$?
        if [ $rc -ne 0 ]
        then
          cat {{wd_deploy_dir_uss}}/cp.{{wd_timestamp}}.log | iconv -f ibm-1047 -t utf-8
          exit $rc
        fi
        exit 0
      ignore_errors: true
      register: wd_zos_module_result
      
    - debug:
        msg: "{{wd_zos_module_result.stdout_lines}}"
      failed_when:
        - wd_zos_module_result.failed == true
        - wd_zos_module.ignore_error_message is not defined or wd_zos_module.ignore_error_message not in wd_zos_module_result.stderr