#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2022. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
---
- name: "[{{current_step_name}}]"
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"
  block:
    - set_fact: 
       wd_ignore_errors_var : "{{wd_zos_module.ignore_errors if wd_zos_module.ignore_errors is defined else False}}"
        
    - name: "[{{current_step_name}}]: Find data set {{wd_zos_module.patterns}}"
      zos_find:
        age: "{{ wd_zos_module.age | default(omit) }}"
        age_stamp: "{{ wd_zos_module.age_stamp | default(omit) }}"
        contains: "{{ wd_zos_module.contains | default(omit) }}"
        directory_blocks: "{{ wd_zos_module.directory_blocks | default(omit) }}"
        excludes: "{{ wd_zos_module.exclude | default(omit) }}"
        patterns: "{{ wd_zos_module.patterns | mandatory }}"
        pds_patterns: "{{ wd_zos_module.pds_patterns | default(omit) }}"
        resource_type: "{{ wd_zos_module.resource_type | default(omit) }}"
        size: "{{ wd_zos_module.size | default(omit) }}"
        volume: "{{ wd_zos_module.volumes | default(omit) }}"
      register: wd_zos_module_result
      ignore_errors: "{{wd_ignore_errors_var}}"

    - name: "set file_matched variable" 
      set_fact: 
       wd_file_matched : "{{True if  wd_zos_module_result.matched > 0 else False}}"
