#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2022, 2023. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
---
- name: "[{{current_step_name}}]"
  block:

    - name: "[{{current_step_name}}]: Retrieve parameters"
      set_fact:
        wd_file_name_include: "{{ lookup('vars',  wd_var_file_name_include) }}"
        wd_file_must_exist_include: "{{ lookup('vars',  wd_var_file_must_exist_include) }}"
      vars:
        wd_var_file_name_include: "{{ wd_step | json_query (\"properties[?key == 'var_file_name_include'].value\") | first | default('include_file_name_default') }}"
        wd_var_file_must_exist_include: "{{ wd_step | json_query (\"properties[?key == 'var_file_must_exist_include'].value\") | first | default('include_file_must_exist_default')}}"

    - name: "[{{current_step_name}}]: Load variables from {{ wd_var_file_name_include }}"
      include_tasks: "include_vars_item.yml"
      with_items: "{{ wd_file_name_include }}"
      when: wd_file_name_include | length > 0