#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2022, 2023. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
---
- name: "[{{current_step_name}}]"
  block:

    - set_fact:
       wd_backup_list_items: "{{ wd_step['artifacts'] | ibm.ibm_zos_wazi_deploy.wd_artifact_list (wd_deploy_dir_uss, wd_types, True, False, wd_no_log_flag )}}"
       wd_backup_list_types: "{{ wd_step['artifacts'] | ibm.ibm_zos_wazi_deploy.wd_type_list ( wd_types, wd_no_log_flag )}}"
      vars:
        wd_var_type: "{{ wd_step | json_query (\"properties[?key == 'var_type'].value\") | first | default(default_types if default_types is defined else 'types') }}"
        wd_types: "{{ lookup('vars',  wd_var_type )}}"

    - name: "[{{current_step_name}}]: Create destination PDS(s)"
      include_tasks: "task_zos_data_set.yml"
      loop: "{{ wd_backup_list_types }}"
      loop_control:
        loop_var: wd_type
      vars:
        wd_zos_module:
          name: "{{ wd_type.pds.backup }}"
          type: "{{ wd_type.pds.spec.type }}"
          space_primary: "{{ wd_type.pds.spec.space_primary }}"
          space_secondary: "{{ wd_type.pds.spec.space_secondary }}"
          space_type: "{{ wd_type.pds.spec.space_type }}"
          record_format: "{{ wd_type.pds.spec.record_format }}"
          record_length: "{{ wd_type.pds.spec.record_length }}"
      when:
        - wd_type.pds is defined
        - member_archive_fast is defined and member_archive_fast | bool == True
        - member_archive_create_dataset is not defined or member_archive_create_dataset | bool == true

    - name: "[{{current_step_name}}]: Copy the member(s) to backup PDS(s)"
      include_tasks: "task_zos_copy.yml"
      with_items: "{{ wd_backup_list_items| default([]) }}"
      vars:
        wd_zos_module:
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
          remote_src: true
          is_binary: "{{ item.is_binary }}"
          ignore_error_message: "{{ 'Source data set ' + item.src + ' does not exist' }}"
          backup: false
          force: true
      when:
        - item.type.pds is defined
        - member_archive_fast is not defined or member_archive_fast | bool == False

    - name: "[{{current_step_name}}]: Copy the member(s) to backup PDS(s) using shell command"
      include_tasks: "task_fast_copy.yml"
      vars:
        wd_zos_module:
          members: "{{ wd_backup_list_items| default([]) }}"
          ignore_missing: true
          is_backup: true
      when:
        - wd_backup_list_items[0].type.pds is defined
        - member_archive_fast is defined and member_archive_fast | bool == True

  tags:
    - member_archive