#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2023. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
---
- name: "[{{current_step_name}}]"
  block:
    - name: "[{{current_step_name}}]: Set variable"
      set_fact:
        wd_copy_list_items: "{{ wd_step['artifacts'] | ibm.ibm_zos_wazi_deploy.wd_artifact_list (wd_deploy_dir_uss, wd_types, False, False, wd_no_log_flag )}}"
      vars:
        wd_var_type: "{{ wd_step | json_query (\"properties[?key == 'var_type'].value\") | first | default(default_types if default_types is defined else 'types') }}"
        wd_types: "{{ lookup('vars',  wd_var_type )}}"

    - name: "[{{current_step_name}}]: Copy the sequential files to destination"
      include_tasks: "task_zos_copy.yml"
      with_items: "{{ wd_copy_list_items| default([]) }}"
      vars:
        wd_zos_module:
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
          remote_src: true
          is_binary: "{{ item.is_binary }}"
          encoding: "{{ item.encoding | default(omit) }}"
          backup: false
          force: true
          dest_data_set: "{{item.type.ds.spec | default(omit) }}"
          volume: "{{item.type.ds.spec.volume | default(omit)}}"
      when:
        - item.type.ds is defined

  when: wd_payload_st is defined and wd_payload_st.stat is defined and wd_payload_st.stat.exists

  tags:
    - sequential_copy
