#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2022. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************

---
- name: "[{{current_step_name}}]"
  block:
    - name: "[{{current_step_name}}]: Set action step variables"
      set_fact:
        task_step_result: {}

    - name : "[{{current_step_name}}]: Retrieve the zowe command"
      include_tasks: "task_zowe_cics_command.yml"

    - name: "[{{current_step_name}}]: Perfom Zowe CLI CICS DEFINE "
      shell: "zowe cics define program {{item}} {{csd_group}} {{zowe_prm}}"
      delegate_to: localhost
      register: cmci_create_program_result
      ignore_errors: true
      with_items: "{{ wd_step['artifacts'] | map(attribute='name') | default([])}}"

    - name: "[{{current_step_name}}]: Collect the cmci create result"
      set_fact:
        task_step_result: "{{ task_step_result | combine ({'cmci_create_program_result':cmci_create_program_result}) }}"

    - name: "[{{current_step_name}}]: Register the cmci create result"
      set_fact:
        deploy_result_tasks_steps: "{{ deploy_result_tasks_steps + [ task_step_result ] }}"
      when: cmci_create_program_result is failed

    - name: "[{{current_step_name}}]: Check if cmci create succeeded'"
      fail:
        msg: "The CMCI_CREATE failed"
      when: cmci_create_program_result is failed

    - name: "[{{current_step_name}}]: Perfom Zowe CLI CICS INSTALL "
      shell: "zowe cics install program {{item}} {{csd_group}} {{zowe_prm}}"
      delegate_to: localhost
      register: cmci_action_install_program_result
      ignore_errors: true
      with_items: "{{ wd_step['artifacts'] | map(attribute='name') | default([])}}"

    - name: "[{{current_step_name}}]: Collect the cmci action install result"
      set_fact:
        task_step_result: "{{ task_step_result | combine ({'cmci_action_install_program_result':cmci_action_install_program_result}) }}"

    - name: "[{{current_step_name}}]: Register the program create result"
      set_fact:
        deploy_result_tasks_steps: "{{ deploy_result_tasks_steps + [ task_step_result ] }}"

    - name: "[{{current_step_name}}]: Check if cmci action install succeeded"
      fail:
        msg: "The CMCI_ACTION install failed"
      when: cmci_action_install_program_result is failed
  tags:
    - cics-cmci-prog-create

  rescue:
    - name : "[{{current_step_name}}]: Store the evidences"
      include_tasks: "wd_failure.yml"